### ISSUE TITLE
Next versioning

### ISSUE THREAD

**Issue by nsams** [vivid-planet/react-admin#226]
1. next branch (contains apollo 3 update, i18n, react 16 || 17) - will be merged into master and deleded after 0.1.0 release
2. 1.0.0 first version, with new name(!!!!)
3. independent
4. changelog file with highlights+incompatibilities in each package (copied into gh release)
5. merge all packages (except date+color picker + rte + stories) into one "@vivid-planet/react-admin"

**Comment by fraxachun** [comment]
1. done
3. done (not changed anyway)
5. #234

**Comment by fraxachun** [comment]
as 2. #234 (last commit)

**Comment by nsams** [comment]
all done...
