### ISSUE TITLE
Remove date-fns

### ISSUE THREAD

**Issue by fraxachun** [vivid-planet/react-admin#239]
Is it possible to remove it? Who would do it?

**Comment by nsams** [comment]
As we don't need it for formatting, there is nothing react-admin can do with it.

applications still can use date-fns if they need it.

I would suggest you remove it as part of the next release

**Comment by rabengraph** [comment]
At the moment it is used for formatting, but this should be refactored so that in future react-intl does the formatting?

**Comment by nsams** [comment]
date-fns has 2 components:
- FormatLocalized: applications should switch to react-intl
- LocaleContextProvider: used by FormatLocalized AND also provides a locale name (useLocaleName) which is used by Date*Picker to use the correct momentjs locale. This also h as to be converted to react-intl somehow

**Comment by dkarnutsch** [comment]
done with #264

**Comment by nsams** [comment]
solved in #264
