### ISSUE TITLE
Naming things is hard

### ISSUE THREAD

**Issue by nsams** [vivid-planet/react-admin#254]
Sorry, but I have to bring this on the table again; now we have:

`import { FinalFormInput, FinalFormCheckbox } from "@vivid-planet/react-admin";`

I'm not very happy with it. Another (not yet discussed) alternative could be:

`import { Input, Checkbox } from "@vivid-planet/react-admin-final-form-fields";`

(create an own package just for the sake of shorter exports)

This would have to stay:

`import { FinalFormDatePicker } from "@vivid-planet/react-admin-date-picker";`

**Comment by kaufmo** [comment]
An alternative could also be this, we can support both

```
import { FinalFormInput, FinalFormCheckbox } from "@vivid-planet/react-admin";
import { Input, Checkbox } from "@vivid-planet/react-admin/final-form";
```

**Comment by nsams** [comment]
yes, another good option

tough I'm not sure if we should export the same thing with two names

**Comment by rabengraph** [comment]
> ```
> import { Input, Checkbox } from "@vivid-planet/react-admin/final-form";
> ```

But like this names are not unique within the package and ide support for autoimport might break:

```
import { Input, Checkbox } from "@vivid-planet/react-admin/final-form";
import { Input, Checkbox } from "@vivid-planet/react-admin";
```
 (which one should be autoimported)

**Comment by rabengraph** [comment]
I think both options are equally ok:

like it is now:
`import { FinalFormInput, FinalFormCheckbox } from "@vivid-planet/react-admin";
`
 and like suggested by niko:

`import { Input, Checkbox } from "@vivid-planet/react-admin-final-form-fields";`

**Comment by nsams** [comment]
with `import { Input, Checkbox } from "@vivid-planet/react-admin-final-form-fields";` autoimport breaks the same way as with `import { Input, Checkbox } from "@vivid-planet/react-admin/final-form";`

but that is not a real problem i'd say, the IDE will present you multiple possible imports and you have to choose.

**Comment by fraxachun** [comment]
I don't like the idea of having two packages when there should be only one as they depend on each other. My vote goes for sticking with the FinalForm prefixes.

**Comment by kaufmo** [comment]
> I don't like the idea of having two packages when there should be only one as they depend on each other. My vote goes for sticking with the FinalForm prefixes.

I think multiple packages because of naming is not an good idea. Prefix or two different export names would be a good alternativ for that

**Comment by kaufmo** [comment]
or this could also be an option export the folder into a ns


index.ts
`export * as FinalForm from "./final-form"`

react.tsx
```
import { FinalForm } from "@vivid-planet/react-admin";
<FinalForm.Input ... />
```
