### ISSUE TITLE
useTableQuery check doesn't handle status code 500 correctly

### ISSUE THREAD

**Issue by Ben-Ho** [vivid-planet/react-admin#65]
somehow data is an empty object ({}) and does not get catched by if (!ret.data) https://github.com/vivid-planet/react-admin/blob/master/packages/react-admin-core/src/table/useTableQuery.ts#L122, resolveTableData is called with an empty object.

is this intended?

**Comment by nsams** [comment]
No, this is not intended :)

please provide a PR

**Comment by Ben-Ho** [comment]
solved in https://github.com/vivid-planet/react-admin/pull/68
